
name: General
# Controls when the action will run. Triggers the workflow on push or successful pr merge
# events but only for the master branch
on:
  push

env:
  BASE_NAME: mtrain-firmware
  REPO_NAME: robojackets
  TAG: testing


# NOTE Much of what I do with run commands directly has other github action specific ways I just didnt care and did it with commands
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-setup
        env:
          TARGET: make
        run: |
          docker pull $REPO_NAME/$BASE_NAME:$TAG &&
          docker create --name $BASE_NAME $REPO_NAME/$BASE_NAME:$TAG $TARGET &&
          docker cp ../mtrain-firmware $BASE_NAME:../mtrain-firmware
      - name: test-build
        run: |
          docker start $BASE_NAME

  style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-setup
        env:
          TARGET: make
        run: |
          docker pull $REPO_NAME/$BASE_NAME:$TAG &&
          docker create --name $BASE_NAME $REPO_NAME/$BASE_NAME:$TAG $TARGET &&
          docker cp ../mtrain-firmware $BASE_NAME:../mtrain-firmware
      - name: run-style
        run: |
          docker start $BASE_NAME


  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-setup
        env:
          TARGET: make
        run: |
          docker pull $REPO_NAME/$BASE_NAME:$TAG &&
          docker create --name $BASE_NAME $REPO_NAME/$BASE_NAME:$TAG $TARGET &&
          docker cp ../mtrain-firmware $BASE_NAME:../mtrain-firmware
      - name: run-tidy
        run: |
          docker start $BASE_NAME
