name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop, collin/ci-and-doxygen]

# NOTE Much of what I do with run commands directly has other github action specific ways I just didnt care and did it with commands
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-firmware:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: testbuild
    steps:
      - name: setup-env
        run: |
          cd $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-build
        run: |
          docker build -t $DOCKER_NAME:latest ./
      - name: test-build
        run: |
          docker run --name $DOCKER_NAME $DOCKER_NAME make

  gen-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: docsbuild
    steps:
      - name: setup-env
        run: |
          cd $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v2
      - name: docker-build
        run: |
          docker build -t $DOCKER_NAME:latest ./
      - name: document
        run: |
          docker run --name $DOCKER_NAME $DOCKER_NAME make docs
      - name: copy
        run: |
          rm -rf generated-docs/ &&
          mkdir -p generated-docs/ &&
          git clone -b gh-pages git://github.com/robojackets/mtrain-firmware generated-docs/ &&
          docker cp $DOCKER_NAME:/home/developer/mtrain-firmware/generated-docs .
      - name: push
        run: |
          cd generated-docs/ &&
          git config --local user.email "action@github.com" &&
          git config --local user.name "GitHub Action" &&
          git add --all -f &&
          git commit -m 'auto-updated documentation' &&
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/robojackets/mtrain gh-pages
